name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm install
      - run: npm test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
